# Ambiente para Programação WEB
# Prof. Taciano Balardin
# apache + php + mysql
version: "1.0"
services:
    www:
        build: .
        container_name: 'www'
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
    db:
        image: mysql:8.0
        container_name: 'mysql'
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 12345 
        volumes:
          - ./database/mysql:/var/lib/mysql
          - ./database/logs:/var/log/mysql
          - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: 'phpmyadmin'
        ports:
            - 8080:80
        environment:
            MYSQL_ROOT_PASSWORD: 12345
        networks:
            - default
networks:
    default:
        driver: bridge